[package]
name = "day-03"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "part1"
path = "src/bin/part1.rs"

[[bin]]
name = "part2"
path = "src/bin/part2.rs"

[dependencies]
utils = { path = "../utils" }
regex="1"